<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Product.aspx.cs" Inherits="TailShopping.Product" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        [dbo].[Products]<div>
        </div><asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="True" 
    DataKeyNames="ProductID"
    AutoGenerateEditButton="True"
    AutoGenerateDeleteButton="True"
    BackColor="#f9f9f9" BorderColor="#ddd" BorderStyle="Solid" BorderWidth="1px"
    CellPadding="6" GridLines="Both">
</asp:GridView>

<asp:SqlDataSource ID="SqlDataSource1" runat="server"
    ConnectionString="<%$ ConnectionStrings:YourConnectionStringName %>"
    SelectCommand="SELECT * FROM Product"
    UpdateCommand="UPDATE Product SET ProductName=@ProductName, Price=@Price, Quantity=@Quantity WHERE ProductID=@ProductID"
    DeleteCommand="DELETE FROM Product WHERE ProductID=@ProductID">
</asp:SqlDataSource>

    </form>
</body>
</html>
